import { Montserrat } from "next/font/google"
import "./../globals.scss"

import React from "react"

import Header from "@/Sections/Header"
import Footer from "@/Sections/Footer"

const MontserratFont = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

async function getData() {
  const res = await fetch("https://gymyx.cro.codes/api/pages/index", {
    next: {
      revalidate: 60,
    },
  })

  if (!res.ok) {
    throw new Error("Failed to fetch data")
  }

  return res.json()
}

export default async function LandingLayout({ children, params }) {
  const { data } = await getData()

  const headerData = data.modules.find(
    (item) => item.section.alias === "header_landing"
  )
  const footerData = data.modules.find(
    (item) => item.section.alias === "footer"
  )

  return (
    <html lang="en">
      <body className={MontserratFont.className}>
        <Header isLanding={true} data={headerData} />
        <main className="main">{children}</main>
        <Footer data={footerData} />
      </body>
    </html>
  )
}
