import { Montserrat } from "next/font/google"
import "./globals.scss"

import Header from "@/Components/Header"
import Footer from "@/Components/Footer"

const MontserratFont = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={MontserratFont.className}>
        <Header />
        <main className="main">{children}</main>
        <Footer />
      </body>
    </html>
  )
}
