import { Montserrat } from "next/font/google"
import "./../globals.scss"

const MontserratFont = Montserrat({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function AccountLayout({ children }) {
  return (
    <html lang="en">
      <body className={MontserratFont.className}>
        <p>обёртска над account</p>
        <main className="main">{children}</main>
      </body>
    </html>
  )
}
